// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: budget/v1/budget.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRow) Reset() {
	*x = SimpleRow{}
	mi := &file_budget_v1_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRow) ProtoMessage() {}

func (x *SimpleRow) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRow.ProtoReflect.Descriptor instead.
func (*SimpleRow) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleRow) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SimpleRow) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ExportBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpreadsheetId string                 `protobuf:"bytes,1,opt,name=spreadsheet_id,json=spreadsheetId,proto3" json:"spreadsheet_id,omitempty"`
	SheetName     string                 `protobuf:"bytes,2,opt,name=sheet_name,json=sheetName,proto3" json:"sheet_name,omitempty"`
	Clear         bool                   `protobuf:"varint,3,opt,name=clear,proto3" json:"clear,omitempty"`
	Rows          []*SimpleRow           `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportBudgetRequest) Reset() {
	*x = ExportBudgetRequest{}
	mi := &file_budget_v1_budget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBudgetRequest) ProtoMessage() {}

func (x *ExportBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBudgetRequest.ProtoReflect.Descriptor instead.
func (*ExportBudgetRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{1}
}

func (x *ExportBudgetRequest) GetSpreadsheetId() string {
	if x != nil {
		return x.SpreadsheetId
	}
	return ""
}

func (x *ExportBudgetRequest) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

func (x *ExportBudgetRequest) GetClear() bool {
	if x != nil {
		return x.Clear
	}
	return false
}

func (x *ExportBudgetRequest) GetRows() []*SimpleRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ExportBudgetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WrittenRange   string                 `protobuf:"bytes,1,opt,name=written_range,json=writtenRange,proto3" json:"written_range,omitempty"`
	Rows           int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	SpreadsheetUrl string                 `protobuf:"bytes,3,opt,name=spreadsheet_url,json=spreadsheetUrl,proto3" json:"spreadsheet_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportBudgetResponse) Reset() {
	*x = ExportBudgetResponse{}
	mi := &file_budget_v1_budget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBudgetResponse) ProtoMessage() {}

func (x *ExportBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBudgetResponse.ProtoReflect.Descriptor instead.
func (*ExportBudgetResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{2}
}

func (x *ExportBudgetResponse) GetWrittenRange() string {
	if x != nil {
		return x.WrittenRange
	}
	return ""
}

func (x *ExportBudgetResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExportBudgetResponse) GetSpreadsheetUrl() string {
	if x != nil {
		return x.SpreadsheetUrl
	}
	return ""
}

type ImportBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpreadsheetId string                 `protobuf:"bytes,1,opt,name=spreadsheet_id,json=spreadsheetId,proto3" json:"spreadsheet_id,omitempty"`
	SheetName     string                 `protobuf:"bytes,2,opt,name=sheet_name,json=sheetName,proto3" json:"sheet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBudgetRequest) Reset() {
	*x = ImportBudgetRequest{}
	mi := &file_budget_v1_budget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBudgetRequest) ProtoMessage() {}

func (x *ImportBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBudgetRequest.ProtoReflect.Descriptor instead.
func (*ImportBudgetRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{3}
}

func (x *ImportBudgetRequest) GetSpreadsheetId() string {
	if x != nil {
		return x.SpreadsheetId
	}
	return ""
}

func (x *ImportBudgetRequest) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

type ImportBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*SimpleRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBudgetResponse) Reset() {
	*x = ImportBudgetResponse{}
	mi := &file_budget_v1_budget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBudgetResponse) ProtoMessage() {}

func (x *ImportBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportBudgetResponse.ProtoReflect.Descriptor instead.
func (*ImportBudgetResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{4}
}

func (x *ImportBudgetResponse) GetRows() []*SimpleRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type DownloadBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBudgetRequest) Reset() {
	*x = DownloadBudgetRequest{}
	mi := &file_budget_v1_budget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBudgetRequest) ProtoMessage() {}

func (x *DownloadBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBudgetRequest.ProtoReflect.Descriptor instead.
func (*DownloadBudgetRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{5}
}

type DownloadBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*SimpleRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBudgetResponse) Reset() {
	*x = DownloadBudgetResponse{}
	mi := &file_budget_v1_budget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBudgetResponse) ProtoMessage() {}

func (x *DownloadBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_budget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBudgetResponse.ProtoReflect.Descriptor instead.
func (*DownloadBudgetResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_budget_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadBudgetResponse) GetRows() []*SimpleRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_budget_v1_budget_proto protoreflect.FileDescriptor

const file_budget_v1_budget_proto_rawDesc = "" +
	"\n" +
	"\x16budget/v1/budget.proto\x12\tbudget.v1\"?\n" +
	"\tSimpleRow\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\x9b\x01\n" +
	"\x13ExportBudgetRequest\x12%\n" +
	"\x0espreadsheet_id\x18\x01 \x01(\tR\rspreadsheetId\x12\x1d\n" +
	"\n" +
	"sheet_name\x18\x02 \x01(\tR\tsheetName\x12\x14\n" +
	"\x05clear\x18\x03 \x01(\bR\x05clear\x12(\n" +
	"\x04rows\x18\x04 \x03(\v2\x14.budget.v1.SimpleRowR\x04rows\"x\n" +
	"\x14ExportBudgetResponse\x12#\n" +
	"\rwritten_range\x18\x01 \x01(\tR\fwrittenRange\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12'\n" +
	"\x0fspreadsheet_url\x18\x03 \x01(\tR\x0espreadsheetUrl\"[\n" +
	"\x13ImportBudgetRequest\x12%\n" +
	"\x0espreadsheet_id\x18\x01 \x01(\tR\rspreadsheetId\x12\x1d\n" +
	"\n" +
	"sheet_name\x18\x02 \x01(\tR\tsheetName\"@\n" +
	"\x14ImportBudgetResponse\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.budget.v1.SimpleRowR\x04rows\"\x17\n" +
	"\x15DownloadBudgetRequest\"B\n" +
	"\x16DownloadBudgetResponse\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.budget.v1.SimpleRowR\x04rows2\x88\x02\n" +
	"\rBudgetService\x12O\n" +
	"\fExportBudget\x12\x1e.budget.v1.ExportBudgetRequest\x1a\x1f.budget.v1.ExportBudgetResponse\x12O\n" +
	"\fImportBudget\x12\x1e.budget.v1.ImportBudgetRequest\x1a\x1f.budget.v1.ImportBudgetResponse\x12U\n" +
	"\x0eDownloadBudget\x12 .budget.v1.DownloadBudgetRequest\x1a!.budget.v1.DownloadBudgetResponseB6Z4gitlab.com/education/users-api/internal/pb/budget/v1b\x06proto3"

var (
	file_budget_v1_budget_proto_rawDescOnce sync.Once
	file_budget_v1_budget_proto_rawDescData []byte
)

func file_budget_v1_budget_proto_rawDescGZIP() []byte {
	file_budget_v1_budget_proto_rawDescOnce.Do(func() {
		file_budget_v1_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_v1_budget_proto_rawDesc), len(file_budget_v1_budget_proto_rawDesc)))
	})
	return file_budget_v1_budget_proto_rawDescData
}

var file_budget_v1_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_budget_v1_budget_proto_goTypes = []any{
	(*SimpleRow)(nil),              // 0: budget.v1.SimpleRow
	(*ExportBudgetRequest)(nil),    // 1: budget.v1.ExportBudgetRequest
	(*ExportBudgetResponse)(nil),   // 2: budget.v1.ExportBudgetResponse
	(*ImportBudgetRequest)(nil),    // 3: budget.v1.ImportBudgetRequest
	(*ImportBudgetResponse)(nil),   // 4: budget.v1.ImportBudgetResponse
	(*DownloadBudgetRequest)(nil),  // 5: budget.v1.DownloadBudgetRequest
	(*DownloadBudgetResponse)(nil), // 6: budget.v1.DownloadBudgetResponse
}
var file_budget_v1_budget_proto_depIdxs = []int32{
	0, // 0: budget.v1.ExportBudgetRequest.rows:type_name -> budget.v1.SimpleRow
	0, // 1: budget.v1.ImportBudgetResponse.rows:type_name -> budget.v1.SimpleRow
	0, // 2: budget.v1.DownloadBudgetResponse.rows:type_name -> budget.v1.SimpleRow
	1, // 3: budget.v1.BudgetService.ExportBudget:input_type -> budget.v1.ExportBudgetRequest
	3, // 4: budget.v1.BudgetService.ImportBudget:input_type -> budget.v1.ImportBudgetRequest
	5, // 5: budget.v1.BudgetService.DownloadBudget:input_type -> budget.v1.DownloadBudgetRequest
	2, // 6: budget.v1.BudgetService.ExportBudget:output_type -> budget.v1.ExportBudgetResponse
	4, // 7: budget.v1.BudgetService.ImportBudget:output_type -> budget.v1.ImportBudgetResponse
	6, // 8: budget.v1.BudgetService.DownloadBudget:output_type -> budget.v1.DownloadBudgetResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_budget_v1_budget_proto_init() }
func file_budget_v1_budget_proto_init() {
	if File_budget_v1_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_v1_budget_proto_rawDesc), len(file_budget_v1_budget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_v1_budget_proto_goTypes,
		DependencyIndexes: file_budget_v1_budget_proto_depIdxs,
		MessageInfos:      file_budget_v1_budget_proto_msgTypes,
	}.Build()
	File_budget_v1_budget_proto = out.File
	file_budget_v1_budget_proto_goTypes = nil
	file_budget_v1_budget_proto_depIdxs = nil
}
