// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: budget/v1/budget.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BudgetService_ExportBudget_FullMethodName   = "/budget.v1.BudgetService/ExportBudget"
	BudgetService_ImportBudget_FullMethodName   = "/budget.v1.BudgetService/ImportBudget"
	BudgetService_DownloadBudget_FullMethodName = "/budget.v1.BudgetService/DownloadBudget"
)

// BudgetServiceClient is the client API for BudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BudgetServiceClient interface {
	ExportBudget(ctx context.Context, in *ExportBudgetRequest, opts ...grpc.CallOption) (*ExportBudgetResponse, error)
	ImportBudget(ctx context.Context, in *ImportBudgetRequest, opts ...grpc.CallOption) (*ImportBudgetResponse, error)
	DownloadBudget(ctx context.Context, in *DownloadBudgetRequest, opts ...grpc.CallOption) (*DownloadBudgetResponse, error)
}

type budgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetServiceClient(cc grpc.ClientConnInterface) BudgetServiceClient {
	return &budgetServiceClient{cc}
}

func (c *budgetServiceClient) ExportBudget(ctx context.Context, in *ExportBudgetRequest, opts ...grpc.CallOption) (*ExportBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_ExportBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) ImportBudget(ctx context.Context, in *ImportBudgetRequest, opts ...grpc.CallOption) (*ImportBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_ImportBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) DownloadBudget(ctx context.Context, in *DownloadBudgetRequest, opts ...grpc.CallOption) (*DownloadBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_DownloadBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetServiceServer is the server API for BudgetService service.
// All implementations must embed UnimplementedBudgetServiceServer
// for forward compatibility.
type BudgetServiceServer interface {
	ExportBudget(context.Context, *ExportBudgetRequest) (*ExportBudgetResponse, error)
	ImportBudget(context.Context, *ImportBudgetRequest) (*ImportBudgetResponse, error)
	DownloadBudget(context.Context, *DownloadBudgetRequest) (*DownloadBudgetResponse, error)
	mustEmbedUnimplementedBudgetServiceServer()
}

// UnimplementedBudgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBudgetServiceServer struct{}

func (UnimplementedBudgetServiceServer) ExportBudget(context.Context, *ExportBudgetRequest) (*ExportBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportBudget not implemented")
}
func (UnimplementedBudgetServiceServer) ImportBudget(context.Context, *ImportBudgetRequest) (*ImportBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportBudget not implemented")
}
func (UnimplementedBudgetServiceServer) DownloadBudget(context.Context, *DownloadBudgetRequest) (*DownloadBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadBudget not implemented")
}
func (UnimplementedBudgetServiceServer) mustEmbedUnimplementedBudgetServiceServer() {}
func (UnimplementedBudgetServiceServer) testEmbeddedByValue()                       {}

// UnsafeBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BudgetServiceServer will
// result in compilation errors.
type UnsafeBudgetServiceServer interface {
	mustEmbedUnimplementedBudgetServiceServer()
}

func RegisterBudgetServiceServer(s grpc.ServiceRegistrar, srv BudgetServiceServer) {
	// If the following call pancis, it indicates UnimplementedBudgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BudgetService_ServiceDesc, srv)
}

func _BudgetService_ExportBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).ExportBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_ExportBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).ExportBudget(ctx, req.(*ExportBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_ImportBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).ImportBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_ImportBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).ImportBudget(ctx, req.(*ImportBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_DownloadBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).DownloadBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_DownloadBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).DownloadBudget(ctx, req.(*DownloadBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BudgetService_ServiceDesc is the grpc.ServiceDesc for BudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "budget.v1.BudgetService",
	HandlerType: (*BudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportBudget",
			Handler:    _BudgetService_ExportBudget_Handler,
		},
		{
			MethodName: "ImportBudget",
			Handler:    _BudgetService_ImportBudget_Handler,
		},
		{
			MethodName: "DownloadBudget",
			Handler:    _BudgetService_DownloadBudget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "budget/v1/budget.proto",
}
